# Generated by Django 2.2.4 on 2019-08-03 09:47

from django.db import migrations, models
import django.db.models.deletion
import galleries.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
                'default_related_name': 'galleries',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(storage=galleries.models.MediaFileSystemStorage(), upload_to=galleries.models.get_upload_path)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('md5sum', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'default_related_name': 'media',
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallerymedia', to='galleries.Gallery')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallerymedia', to='galleries.Media')),
            ],
            options={
                'verbose_name': 'gallery media',
                'verbose_name_plural': 'gallery media',
                'default_related_name': 'gallerymedia',
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='media',
            field=models.ManyToManyField(related_name='galleries', through='galleries.GalleryMedia', to='galleries.Media'),
        ),
    ]
