# Generated by Django 2.2.4 on 2019-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='media',
            field=models.ManyToManyField(related_name='gallery_media', through='galleries.GalleryMedia', to='galleries.Media'),
        ),
    ]
